hm_5
AleR111/aler111.github.io pull request #7
Opened 2021-03-08 09:14 UTC by AleR111

2021-03-08 09:19 UTC, AleR111 reviewed
lesson5

2021-03-14 18:13 UTC, Om1X requested changes

2021-03-14 18:13 UTC, Om1X commented on Lesson5/hm_5/catalog.js
> +        })
Перегрузка циклами, достаточно одного. Стилизация должна быть через css

2021-03-14 18:13 UTC, Om1X commented on Lesson5/hm_5/catalog.js
> +        this.goodsCart.goods.push(this.catalog.goods[this.buttonNum])
вместо "прямого" изменения данных, лучше в корзине сделать метод добавления в корзину и его уже тут вызывать, передавая товар.

2021-03-15 16:26 UTC, merged